//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABONOS
    {
        public decimal Nro_Abono { get; set; }
        public System.DateTime Fecha_Monto { get; set; }
        public decimal Monto { get; set; }
        public decimal CONTRATO_NRO_Contrato { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual DETALLE_ABONO DETALLE_ABONO { get; set; }
    }
}
