//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABONOS
    {
        public decimal Nro_Abono { get; set; }
        public System.DateTime Fecha_Monto { get; set; }
        public decimal Monto { get; set; }
        public decimal CONTRATO_NRO_Contrato { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual DETALLE_ABONO DETALLE_ABONO { get; set; }
    }
}
