//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public string ID_CLIENTE { get; set; }
        public string Rut_Cliente { get; set; }
        public string Nombre_Completo { get; set; }
        public string Apellido_Completo { get; set; }
        public string Corre_Electronico { get; set; }
        public Nullable<decimal> Telefono { get; set; }
        public string Tipo_Cliente { get; set; }
        public decimal CONTRATO_NRO_Contrato { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
