//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public string ID_CLIENTE { get; set; }
        public string Rut_Cliente { get; set; }
        public string Nombre_Completo { get; set; }
        public string Apellido_Completo { get; set; }
        public string Corre_Electronico { get; set; }
        public Nullable<decimal> Telefono { get; set; }
        public string Tipo_Cliente { get; set; }
        public decimal CONTRATO_NRO_Contrato { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
