//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ABONO
    {
        public string Nombre_Depositante { get; set; }
        public string Tipo_Documento { get; set; }
        public decimal Monto { get; set; }
        public string REPRESENTANTE_CURSO_RUT_Representante { get; set; }
        public decimal ABONOS_Nro_Abono { get; set; }
    
        public virtual ABONOS ABONOS { get; set; }
        public virtual REPRESENTANTE_CURSO REPRESENTANTE_CURSO { get; set; }
    }
}
