//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ABONO
    {
        public string Nombre_Depositante { get; set; }
        public string Tipo_Documento { get; set; }
        public decimal Monto { get; set; }
        public string REPRESENTANTE_CURSO_RUT_Representante { get; set; }
        public decimal ABONOS_Nro_Abono { get; set; }
    
        public virtual ABONOS ABONOS { get; set; }
        public virtual REPRESENTANTE_CURSO REPRESENTANTE_CURSO { get; set; }
    }
}
