//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONTRATO
    {
        public Nullable<decimal> Descuento { get; set; }
        public decimal Valor_Neto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal CONTRATO_NRO_Contrato { get; set; }
        public string PRODUCTOS_ID_Producto { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
