//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONTRATO
    {
        public Nullable<decimal> Descuento { get; set; }
        public decimal Valor_Neto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal CONTRATO_NRO_Contrato { get; set; }
        public string PRODUCTOS_ID_Producto { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
