//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ONTOUREntities : DbContext
    {
        public ONTOUREntities()
            : base("name=ONTOUREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABONOS> ABONOS { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CONTRATO> CONTRATO { get; set; }
        public virtual DbSet<DETALLE_ABONO> DETALLE_ABONO { get; set; }
        public virtual DbSet<DETALLE_CONTRATO> DETALLE_CONTRATO { get; set; }
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<REPRESENTANTE_CURSO> REPRESENTANTE_CURSO { get; set; }
        public virtual DbSet<SEGURO> SEGURO { get; set; }
    }
}
