//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPRESENTANTE_CURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPRESENTANTE_CURSO()
        {
            this.DETALLE_ABONO = new HashSet<DETALLE_ABONO>();
        }
    
        public string RUT_Representante { get; set; }
        public string Nombre_Completo { get; set; }
        public string Curso { get; set; }
        public string Colegio { get; set; }
        public string Corre_Electronico { get; set; }
        public Nullable<decimal> Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ABONO> DETALLE_ABONO { get; set; }
    }
}
