//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURO
    {
        public decimal ID_Seguro { get; set; }
        public string Nombre_Seguro { get; set; }
        public decimal Monto_Seguro { get; set; }
        public decimal CONTRATO_NRO_Contrato { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
